schema:
  - http://localhost:8080/graphql
documents:
  - src/main/resources/graphql/**/*.graphql
generates:
  src/main/resources/graphql:
    config:
      package: rememberit.
    plugins:
      - java